[SPARK_APP_CONFIGS]
saprk.app.name = SparkSqlTableDemo
spark.master = local[3]

# Setting up the dataset file name that are used in this application
file_name_csv = flight-time.csv
file_name_json = flight-time.json
file_name_parquet = flight-time.parquet

# Added a shuffle sort partitions to control the no of partitions of the spark dataFrame in the spark applicaiton
spark.sql.shuffle.partitions = 2