[SPARK_APP_CONFIGS]
saprk.app.name = SparkSqlTableDemo
spark.master = local[3]

# For dataFrame join operation
# Set the shuffle partitions
spark.sql.shuffle.partitions = 3
# Disable AQE for deterministic partition behavior 
spark.sql.adaptive.enabled = false

# Setting up the dataset file name that are used in this application
file_name_csv = flight-time.csv
file_name_json = flight-time.json
file_name_parquet = flight-time.parquet
file_name_text = apache_logs.txt

# Tell spark to save the created table in this database
db_name = airline_db
flight_table_name = flight_data